### ISSUE TITLE
Listing of rules contain strange characters

### ISSUE THREAD

**Issue by matejak** [OpenSCAP/OVAL-visualization-as-graph#133]
Running

`arf-to-json tests/test_data/ssg-fedora-ds-arf.xml creat`

yields

```
== The Rule IDs ==
'xccdf_org.ssgproject.content_rule_audit_rules_unsuccessful_file_modification_creat\b'
'xccdf_org.ssgproject.content_rule_audit_rules_unsuccessful_file_modification_open_o_creat\b'
'xccdf_org.ssgproject.content_rule_audit_rules_unsuccessful_file_modification_openat_o_creat\b'
'xccdf_org.ssgproject.content_rule_audit_rules_unsuccessful_file_modification_open_by_handle_at_o_creat\b'
You haven't got installed inquirer lib. Please copy id rule with you want use and put it in command
```

Notice the `\b` that follow rule IDs, those look like some omissions.

**Comment by Honny1** [comment]
`\b` is the end of a word in a regular expression, because in some cases ID of rule is differed only in the last words. Therefore, I ended the rule ID with `\b` and enclosed it in quotation marks. The user can simply copy and paste the line with the rule he wants.
See example:
```
xccdf_org.ssgproject.content_rule_audit_rules_unsuccessful_file_modification_open
xccdf_org.ssgproject.content_rule_audit_rules_unsuccessful_file_modification_open_by_handle_at_rule_order
xccdf_org.ssgproject.content_rule_audit_rules_unsuccessful_file_modification_open_by_handle_at_o_creat
```
If the user wanted to generate a rule named `xccdf_org.ssgproject.content_rule_audit_rules_unsuccessful_file_modification_open` and used only the rule ID, he would always see the list of rules like in the example.

I can change `\b` to the standard start and end for a regular expression. It will be clearer.

**Comment by matejak** [comment]
Looking back, it's probably the label that needed fixing. But I think that the current form of the output is better.
